-- permissions.lua: permissions selectable per project.
-- Same list as user_permission in the host init.lua (manifest template);
-- the builder can only keep permissions present in that manifest.
local L = {
  { "ACCESS_COARSE_LOCATION",      "Lokasi perkiraan" },
  { "ACCESS_FINE_LOCATION",        "Lokasi akurat (GPS)" },
  { "ACCESS_NETWORK_STATE",        "Lihat status jaringan" },
  { "ACCESS_WIFI_STATE",           "Lihat status Wi-Fi" },
  { "ANSWER_PHONE_CALLS",          "Menjawab panggilan telepon" },
  { "BATTERY_STATS",               "Statistik baterai" },
  { "BIND_ACCESSIBILITY_SERVICE",  "Layanan aksesibilitas" },
  { "BLUETOOTH",                   "Bluetooth" },
  { "BLUETOOTH_ADMIN",             "Kelola Bluetooth" },
  { "CALL_PHONE",                  "Melakukan panggilan telepon" },
  { "CAMERA",                      "Kamera" },
  { "CHANGE_NETWORK_STATE",        "Ubah status jaringan" },
  { "CHANGE_WIFI_STATE",           "Ubah status Wi-Fi" },
  { "CLEAR_APP_CACHE",             "Hapus cache aplikasi" },
  { "DOWNLOAD_WITHOUT_NOTIFICATION", "Unduh tanpa notifikasi" },
  { "FOREGROUND_SERVICE",          "Layanan latar depan" },
  { "GET_PACKAGE_SIZE",            "Ukuran paket aplikasi" },
  { "INSTALL_SHORTCUT",            "Pasang pintasan" },
  { "INTERNET",                    "Akses internet" },
  { "KILL_BACKGROUND_PROCESSES",   "Matikan proses latar belakang" },
  { "READ_CALL_LOG",               "Baca riwayat panggilan" },
  { "READ_CONTACTS",               "Baca kontak" },
  { "READ_EXTERNAL_STORAGE",       "Baca penyimpanan" },
  { "READ_FRAME_BUFFER",           "Baca frame buffer layar" },
  { "READ_LOGS",                   "Baca log sistem" },
  { "READ_PHONE_STATE",            "Baca status telepon" },
  { "READ_SMS",                    "Baca SMS" },
  { "RECORD_AUDIO",                "Rekam audio" },
  { "REQUEST_INSTALL_PACKAGES",    "Minta pasang aplikasi" },
  { "SEND_SMS",                    "Kirim SMS" },
  { "SET_WALLPAPER",               "Ubah wallpaper" },
  { "SYSTEM_ALERT_WINDOW",         "Tampil di atas aplikasi lain" },
  { "VIBRATE",                     "Getar" },
  { "WAKE_LOCK",                   "Tahan layar/CPU tetap aktif" },
  { "WRITE_CALL_LOG",              "Tulis riwayat panggilan" },
  { "WRITE_CONTACTS",              "Tulis kontak" },
  { "WRITE_EXTERNAL_STORAGE",      "Tulis penyimpanan" },
  { "WRITE_SETTINGS",              "Ubah pengaturan sistem" },
  { "WRITE_SMS",                   "Tulis SMS" },
}
return L
